<!-- <div style='float:right'><img width=200 src="hse-logo.jpg" alt="HSE logo"></img></div> -->
<div style='float:left'><img width=400 src="python_logo.png" alt="Python"></img></div>

<div style='float:right'>

<h1 align='center'>Язык программирования Python</h1>

<h2 align='right'>Бобер Станислав Алексеевич</h2>
<h3 align='right'>Ст. преп. Департамента Прикладной Математики</h3>
<h3 align='right'>e-mail: sbober@hse.ru, stas.bober@gmail.com</h3>
</div>


<h1 align='center'>Лекция 2. Модуль NumPy</h1>

## Основной объект - многомерный массив (ndarray)

### Одномерный массив

In [152]:
# подключение модуля и сокращение названия для удобства
import numpy as np

np.set_printoptions(precision=3) # настройка вывода элементов массива не более 3 цифр после запятой


In [153]:
# создание одномерного массива на основе списка
arr = np.array([1, 3, 6, 4, 7, 2, 9, 5, 8])

print('%25s'%'тип объекта:', type(arr))
print('%25s'%'тип элемента массива:', arr.dtype)
print('%25s'%'форма массива:', arr.shape)
print('%25s'%'содержимое массива:', arr)
arr


             тип объекта: <class 'numpy.ndarray'>
    тип элемента массива: int32
           форма массива: (9,)
      содержимое массива: [1 3 6 4 7 2 9 5 8]


array([1, 3, 6, 4, 7, 2, 9, 5, 8])

In [154]:
# создание одномерного массива с заданием типа элемента

for dt in [np.int32, np.float64, np.bool]:
    arr = np.array([1, 3, 0, 4, 7, 0, 9, 5, 8], dtype=dt)
    print('%25s %s %s'%(dt, type(arr), arr))


    <class 'numpy.int32'> <class 'numpy.ndarray'> [1 3 0 4 7 0 9 5 8]
  <class 'numpy.float64'> <class 'numpy.ndarray'> [1. 3. 0. 4. 7. 0. 9. 5. 8.]
           <class 'bool'> <class 'numpy.ndarray'> [ True  True False  True  True False  True  True  True]


In [155]:
# аналог range - создание последовательности с заданным шагом

arr = np.arange(0, 5, 0.5)
arr


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [156]:
# linspace - равномерное размещение заданного количества точек в отрезке

print('%25s'%'обычный linspace',       np.linspace(0, 10, 11))
print('%25s'%'с возвращением шага',    np.linspace(0, 10, 11, retstep=True))
print('%25s'%'не включая правый край', np.linspace(0, 10, 11, endpoint=False))


         обычный linspace [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
      с возвращением шага (array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)
   не включая правый край [0.    0.909 1.818 2.727 3.636 4.545 5.455 6.364 7.273 8.182 9.091]


In [157]:
# срезы (slice) - это новые представления (view) массива

arr = np.arange(0, 5, 0.5)
arr[::2], arr[-3:]


(array([0., 1., 2., 3., 4.]), array([3.5, 4. , 4.5]))

In [158]:
# изменение части массива при помощи среза
# задействован broadcasting - о нем далее

print(arr)
arr[::2] = 0
print(arr)


[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.  0.5 0.  1.5 0.  2.5 0.  3.5 0.  4.5]


### Многомерный массив

In [159]:
# создание двумерного массива на основе списка списков
arr = np.array([[1, 3, 6], [4, 7, 2], [9, 5, 8]])

print('shape', arr.shape)
arr


shape (3, 3)


array([[1, 3, 6],
       [4, 7, 2],
       [9, 5, 8]])

In [160]:
# создание двумерного массива при помощи метода reshape
arr = np.arange(9).reshape(3, 3)

print('shape', arr.shape)
arr


shape (3, 3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [161]:
# транспонирование массива

print(arr.T)
print(np.transpose(arr))


[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [244]:
# срезы многомерного массива

print('arr\n', arr)
print('строка 2', arr[2, :])
print('столбец 1\n', arr[:, 1])
print('каждая вторая строка, столбцы 1,2\n', arr[::2, 1:3])

arr
 [[ 0.  1.  2.  3.  4.]
 [15.  0.  0.  0.  5.]
 [14.  0.  0.  0.  6.]
 [13.  0.  0.  0.  7.]
 [12. 11. 10.  9.  8.]]
строка 2 [14.  0.  0.  0.  6.]
столбец 1
 [ 1.  0.  0.  0. 11.]
каждая вторая строка, столбцы 1,2
 [[ 1.  2.]
 [ 0.  0.]
 [11. 10.]]


### Broadcasting

<img src="numpy_broadcasting.png"></img>

In [245]:
# механизм broadcasting
# большинство операций над массивами "приводят" их к максимальным размерам, если количество измерений совпадает

arr1 = np.array([range(5)]).T*10
arr2 = np.array(range(5))

print('arr1:\n', arr1)
print('arr2:', arr2)

arr = arr1+arr2
arr


arr1:
 [[ 0]
 [10]
 [20]
 [30]
 [40]]
arr2: [0 1 2 3 4]


array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

### Полезные функции для создания массивов

In [164]:
# пустой массив - не инициализирует значения элементов
np.empty((5,5))


array([[0.5  , 0.363, 0.466, 0.399, 0.269],
       [0.841, 0.816, 0.176, 0.209, 0.046],
       [0.44 , 0.802, 0.193, 0.439, 0.601],
       [0.02 , 0.277, 0.823, 0.118, 0.302],
       [0.493, 0.49 , 0.196, 0.602, 0.842]])

In [165]:
# массив из нулей
np.zeros((5,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [166]:
# массив из единиц
np.ones((5,5))


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [167]:
# единичная матрица
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [168]:
# единичную диагональ задает параметр k
np.eye(5, k=-1)


array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [169]:
# создать матрицу с заданной диагональю
np.diag([1,2,3], k=1)


array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [170]:
# достать заданную диагональ из матрицы
print(arr)
np.diag(arr, k=-1)


[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


array([10, 21, 32, 43])

### Генерация псевдослучайных последовательностей

In [195]:
import numpy.random as npr
npr.seed(1234)

# равномерно распределенные случайные числа в полуинтервале [0, 1)
npr.rand(5, 5)


array([[0.192, 0.622, 0.438, 0.785, 0.78 ],
       [0.273, 0.276, 0.802, 0.958, 0.876],
       [0.358, 0.501, 0.683, 0.713, 0.37 ],
       [0.561, 0.503, 0.014, 0.773, 0.883],
       [0.365, 0.615, 0.075, 0.369, 0.933]])

In [172]:
# нормально распределенные случайные числа с заданным средним и стандартным отклонением
npr.normal(10, 2, size=(5,5))


array([[10.24 ,  9.339, 14.033,  8.814, 10.699],
       [13.617, 11.264, 10.779,  8.617,  8.558],
       [ 8.954,  7.595, 11.323, 11.682,  9.395],
       [10.235,  9.087, 10.444,  6.758, 10.623],
       [ 8.965, 10.165, 11.554,  9.253, 10.304]])

In [203]:
# выбрать псевдослучайный элемент из последовательности

for _ in range(20):
    print(npr.choice(list('последовательность')), end=' ')
    

о в е л о ь н п ь д ь д н т т а ь о ь с 

In [205]:
# перемешать элементы изменяемой последовательности
lst = list(range(20))
print('initial list', lst)
npr.shuffle(lst)
print('shuffled list', lst)


initial list [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
shuffled list [11, 1, 10, 0, 8, 15, 17, 9, 12, 19, 16, 3, 4, 7, 6, 13, 5, 2, 14, 18]


### Поэлементные операции над массивами

In [177]:
arr1 = np.arange(5)
arr2 = np.arange(10, 15)

print('            сложение:', arr1+arr2)
print('           умножение:', arr1*arr2)
print(' умножение на скаляр:', arr1*5)
print('возведение в степень:', arr1**2)
print('           сравнение:', arr1<arr2)


            сложение: [10 12 14 16 18]
           умножение: [ 0 11 24 39 56]
 умножение на скаляр: [ 0  5 10 15 20]
возведение в степень: [ 0  1  4  9 16]
           сравнение: [ True  True  True  True  True]


### Простая обработка массивов

In [174]:
# поиск минимума, максимума, среднего, стандартного отклонения
arr = npr.rand(10)

print(' arr:', arr)
print(' min:', np.min(arr))
print(' max:', np.max(arr))
print('mean:', np.mean(arr))
print(' std:', np.std(arr))


 arr: [0.336 0.247 0.179 0.651 0.54  0.234 0.831 0.059 0.631 0.109]
 min: 0.05875157391438379
 max: 0.8310728425249804
mean: 0.3817407098273086
 std: 0.2496099059500095


In [175]:
# поиск минимума, максимума, среднего, стандартного отклонения вдоль заданного измерения

arr = npr.rand(5, 5)

print(' arr:\n', arr)
print(' min:', np.min(arr, axis=0))
print(' max:', np.max(arr, axis=0))
print('mean:', np.mean(arr, axis=0))
print(' std:', np.std(arr, axis=0))


 arr:
 [[0.465 0.737 0.885 0.573 0.012]
 [0.478 0.124 0.346 0.393 0.839]
 [0.63  0.845 0.199 0.365 0.006]
 [0.419 0.683 0.65  0.88  0.713]
 [0.994 0.877 0.496 0.905 0.901]]
 min: [0.419 0.124 0.199 0.365 0.006]
 max: [0.994 0.877 0.885 0.905 0.901]
mean: [0.597 0.653 0.515 0.623 0.494]
 std: [0.211 0.274 0.238 0.231 0.401]


In [187]:
# поиск индексов минимального, максимального, ненулевого элементов или по условию
arr = npr.rand(5, 5)
arr[arr<0.5] = 0

print('arr:\n', arr)
print('argmin:', np.argmin(arr))
print('argmax:', np.argmax(arr))
print('argwhere:\n', np.argwhere(arr))


arr:
 [[0.    0.    0.    0.    0.517]
 [0.689 0.718 0.    0.    0.846]
 [0.609 0.928 0.    0.815 0.572]
 [0.    0.    0.717 0.646 0.   ]
 [0.972 0.982 0.    0.547 0.514]]
argmin: 0
argmax: 21
argwhere:
 [[0 4]
 [1 0]
 [1 1]
 [1 4]
 [2 0]
 [2 1]
 [2 3]
 [2 4]
 [3 2]
 [3 3]
 [4 0]
 [4 1]
 [4 3]
 [4 4]]


### Специальная индексация и маскирование (fancy indexing and masking)

In [176]:
arr = np.arange(10)[::-1]
print(arr)

arr[[1,5,7]] # получить представление части массива, заданной индексами 1,5,7


[9 8 7 6 5 4 3 2 1 0]


array([8, 4, 2])

In [129]:
arr = np.arange(16).reshape(4,4)
print(arr)

idx = [1,2,3]
arr[idx, idx] # получить диагональные элементы с индексами (1,1),(2,2),(3,3)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([ 5, 10, 15])

In [133]:
arr = np.arange(16).reshape(4,4)
print(arr)

idx = np.array([[1,2,3]])
arr[idx.T, idx] # получить подматрицу на пересечении столбцов и строк с индексами 1,2,3


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [141]:
idx = [1,2,3]

print(np.ix_(idx, idx)) # создает "открытую решетку" из индексов
arr[np.ix_(idx, idx)]


(array([[1],
       [2],
       [3]]), array([[1, 2, 3]]))


array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [147]:
arr = npr.rand(10)

mask = arr < 0.5 # создание маски

print('   arr:', arr)
print('  mask:', mask)
print('result:', arr[mask])

   arr: [5.111e-04 2.007e-01 1.649e-01 9.368e-01 6.698e-01 3.449e-01 2.384e-01
 2.686e-01 7.152e-01 8.857e-01]
  mask: [ True  True  True False False  True  True  True False False]
result: [0.001 0.201 0.165 0.345 0.238 0.269]


In [150]:
arr = npr.rand(5, 5)

mask = arr < 0.5 # создание маски

print('arr:\n', arr)
print('mask:\n', mask)
print('result:\n', arr[mask])

arr:
 [[0.5   0.363 0.466 0.399 0.269]
 [0.841 0.816 0.176 0.209 0.046]
 [0.44  0.802 0.193 0.439 0.601]
 [0.02  0.277 0.823 0.118 0.302]
 [0.493 0.49  0.196 0.602 0.842]]
mask:
 [[ True  True  True  True  True]
 [False False  True  True  True]
 [ True False  True  True False]
 [ True  True False  True  True]
 [ True  True  True False False]]
result:
 [0.5   0.363 0.466 0.399 0.269 0.176 0.209 0.046 0.44  0.193 0.439 0.02
 0.277 0.118 0.302 0.493 0.49  0.196]


### Склеивание, поворот, отражение и др.

In [220]:
# склеить массивы горизонтально
arr = np.arange(5)

print('   arr:', arr)

np.hstack((arr, arr))


   arr: [0 1 2 3 4]


array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [221]:
# склеить массивы горизонтально
arr = np.arange(5).reshape(-1,1)

print('   arr:\n', arr)

np.hstack((arr, arr))


   arr:
 [[0]
 [1]
 [2]
 [3]
 [4]]


array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [222]:
# склеить массивы вертикально
arr = np.arange(5)

print('   arr:', arr)

np.vstack((arr, arr))


   arr: [0 1 2 3 4]


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [223]:
# склеить массивы вертикально
arr = np.arange(5).reshape(-1,1)

print('   arr:\n', arr)
np.vstack((arr, arr))


   arr:
 [[0]
 [1]
 [2]
 [3]
 [4]]


array([[0],
       [1],
       [2],
       [3],
       [4],
       [0],
       [1],
       [2],
       [3],
       [4]])

In [227]:
# сложить две матрицы в трехмерный массив
arr = np.arange(9).reshape(3,3)

stack = np.stack((arr, arr), axis=2)
print(stack.shape)
stack


(3, 3, 2)


array([[[0, 0],
        [1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4],
        [5, 5]],

       [[6, 6],
        [7, 7],
        [8, 8]]])

In [231]:
# циклический сдвиг вдоль оси
arr = np.arange(9).reshape(3,3)
print('arr:', arr)

np.roll(arr, 1, axis=1)


arr: [[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 0, 1],
       [5, 3, 4],
       [8, 6, 7]])

In [232]:
# отражение верх-низ
np.flipud(arr)


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [233]:
# отражение лево-право
np.fliplr(arr)


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [243]:
# поворот массива на 90, 180, 270 градусов по/против часовой стрелки
arr = np.zeros((5,5))

for i in range(4):
    arr[0, :-1] = range(i*4, (i+1)*4)
    arr = np.rot90(arr, 1)
arr

array([[ 0.,  1.,  2.,  3.,  4.],
       [15.,  0.,  0.,  0.,  5.],
       [14.,  0.,  0.,  0.,  6.],
       [13.,  0.,  0.,  0.,  7.],
       [12., 11., 10.,  9.,  8.]])

### Линейная алгебра

In [185]:
# норма вектора
np.linalg.norm([3,4])

5.0

In [188]:
alpha = np.radians(30)
s, c = np.sin(alpha), np.cos(alpha)
arr = np.array([[c, s], [-s, c]])

np.linalg.eig(arr) # собственные числа и собственные векторы

(array([0.866+0.5j, 0.866-0.5j]), array([[0.707+0.j   , 0.707-0.j   ],
        [0.   +0.707j, 0.   -0.707j]]))

In [194]:
# решить систему линейных уравнений

K = np.eye(3)
K[2,1]=2.
F = np.array([0, 1, 3])

print('solve: K*U=F')
print('K\n', K)
print('F', F)
print('U', np.linalg.solve(K, F))

solve: K*U=F
K
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 2. 1.]]
F [0 1 3]
U [0. 1. 1.]


In [179]:
arr1 = np.arange(5)
arr2 = np.arange(10, 15)

# скалярное произведение
print(arr1.dot(arr2))
print(arr1@arr2)
print(np.dot(arr1, arr2))

130
130
130


In [181]:
arr1 = np.arange(16).reshape(4,4)
arr2 = np.eye(4)*2

# матричное умножение
print(arr1.dot(arr2))
print(arr1@arr2)
print(np.dot(arr1, arr2))

[[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]
 [24. 26. 28. 30.]]
[[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]
 [24. 26. 28. 30.]]
[[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]
 [24. 26. 28. 30.]]


## Вопросы и дополнения к лекции


[Scientific Python Lectures](https://github.com/jrjohansson/scientific-python-lectures)

[100 Numpy Exercises](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_no_solution.ipynb)